version: 0.2
os: linux

files:
  - source: scripts
    destination: /opt/scripts

hooks:
  AfterInstall:
    - location: /opt/scripts/install_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /opt/scripts/start_docker.sh
      timeout: 300
      runas: root
